version: '3.3'

services:
  apigive:
    #see https://github.com/docker/build-push-action/tree/releases/v1#tag_with_ref

    # is sometime you want to rollback you can change the tag manually in server( not commit to git)
    # from master to your desired commit hash and the run command:
    # 1. docker-compose -f docker-compose-staging.yml pull
    # 2. docker-compose -f docker-compose-staging.yml down
    # 3. docker-compose -f docker-compose-staging.yml up -d
    image: ghcr.io/giveth/apigive:main
    command: npm run start:server:production
    restart: always
    environment:
      - NODE_ENV=production
    volumes:
      # You should have a staging.env file in the config folder
      - type: bind
        source: ./config
        target: /usr/src/app/dist/config
      - type: bind
        source: ./config
        target: /usr/src/app/config
      - type: bind
        source: ./logs
        target: /usr/src/app/dist/logs
    ports:
      - "3040:3040"

  redis-apigive:
    # it's better to not using latest tag, maybe latest tag have some breaking changes
    image: bitnami/redis:5.0.9-debian-10-r142
    container_name: redis-apigive
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: always
    volumes:
      - redis-apigive-data:/bitnami/redis/data

volumes:
  redis-apigive-data:
